CREATE TABLE Teams (
    TeamID INT PRIMARY KEY,
    TeamName VARCHAR(255) NOT NULL
);

CREATE TABLE Players (
    PlayerID INT PRIMARY KEY,
    PlayerName VARCHAR(255) NOT NULL,
    TeamID INT,
    FOREIGN KEY (TeamID) REFERENCES Teams(TeamID)
);
INSERT INTO Players (PlayerID, PlayerName, TeamID)
VALUES (1, 'Robert Lewandowski', 1),
       (2, 'Karol Świderski', 1),
       (3, 'Kacper Kozłowski', 1),
       (4, 'Antoine Griezmann', 2),
       (5, 'Kylian Mbappé', 2),
       (6, 'Ousmane Dembélé', 2),
       (7, 'Manuel Neuer', 3),
       (8, 'Toni Kroos', 3),
       (9, 'Leroy Sané', 3),
       (10, 'Sergio Ramos', 4),
       (11, 'Sergio Busquets', 4),
       (12, 'Gerard Moreno', 4),
       (13, 'Harry Kane', 5),
       (14, 'Raheem Sterling', 5),
       (15, 'Marcus Rashford', 5),
       (16, 'Gianluigi Donnarumma', 6),
       (17, 'Leonardo Bonucci', 6),
       (18, 'Federico Chiesa', 6),
       (19, 'Kevin De Bruyne', 7),
       (20, 'Romelu Lukaku', 7),
       (21, 'Thibaut Courtois', 7),
       (22, 'Cristiano Ronaldo', 8),
       (23, 'Bernardo Silva', 8),
       (24, 'Diogo Jota', 8),
       (25, 'Memphis Depay', 9),
       (26, 'Georginio Wijnaldum', 9),
       (27, 'Denzel Dumfries', 9),
       (28, 'Alexander Isak', 10),
       (29, 'Emil Forsberg', 10),
       (30, 'Victor Lindelöf', 10),
       (31, 'Xherdan Shaqiri', 11),
       (32, 'Granit Xhaka', 11),
       (33, 'Breel Embolo', 11),
       (34, 'Kasper Schmeichel', 12),
       (35, 'Christian Eriksen', 12),
       (36, 'Yussuf Poulsen', 12),
       (37, 'David Alaba', 13),
       (38, 'Marko Arnautović', 13),
       (39, 'Marcel Sabitzer', 13),
       (40, 'Jan Bednarek', 1),
       (41, 'Kamil Glik', 1),
       (42, 'Grzegorz Krychowiak', 1),
       (43, 'Karol Linetty', 1),
       (44, 'Mateusz Klich', 1),
       (45, 'Piotr Zieliński', 1),
       (46, 'Kacper Kozłowski', 1),
       (47, 'Tomasz Kędziora', 1),
       (48, 'Bartosz Bereszyński', 1),
       (49, 'Maciej Rybus', 1),
       (50, 'Wojciech Szczęsny', 1),
       (51, 'Łukasz Fabiański', 1),
       (52, 'Rafał Augustyniak', 2),
       (53, 'Lucas Digne', 2),
       (54, 'Lucas Hernandez', 2),
       (55, 'Benjamin Pavard', 2),
       (56, 'Presnel Kimpembe', 2),
       (57, 'Jules Kounde', 2),
       (58, 'Thomas Lemar', 2),
       (59, 'Paul Pogba', 2),
       (60, 'Golo Kante', 2),
       (61, 'Antoine Griezmann', 2),
       (62, 'Kylian Mbappe', 2),
       (63, 'Ousmane Dembele', 2),
       (64, 'Hugo Lloris', 2),
       (65, 'Manuel Neuer', 3),
       (66, 'Bernd Leno', 3),
       (67, 'Kevin Trapp', 3),
       (68, 'Matthias Ginter', 3),
       (69, 'Antonio Rudiger', 3),
       (70, 'Mats Hummels', 3),
       (71, 'Niklas Sule', 3),
       (72, 'Robin Gosens', 3),
       (73, 'Joshua Kimmich', 3),
       (74, 'Leon Goretzka', 3),
       (75, 'Toni Kroos', 3),
       (76, 'Ilkay Gundogan', 3);
